title: TODO(instructor) - insert-your-title-here Workshop
logo: /assets/img/logo.gif
description: TODO(instructor) - list the days your workshop are being taught here
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
