title: Intermediate Topics in Machine Learning and Deep Learning Workshop
logo: /assets/img/logo.gif
description: Wednesday, August 17, 2022 (1:00 pm to 4:00 pm PDT) & Friday, August 19, 2022 (1:00 pm to 4:00 pm PDT)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
