title: Intermediate Topics in Machine Learning and Deep Learning Workshop
logo: /assets/img/logo.gif
description: Wednesday, August 17, 2022 (1:00 pm to 4:00 pm PT) & Friday, August 19, 2022 (1:00 pm to 4:00 pm PT)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
